# Generated by Django 4.1.7 on 2023-05-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("songs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="id_songs",
            field=models.CharField(
                max_length=300, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="name_song",
            field=models.CharField(max_length=300),
        ),
    ]
